### ISSUE TITLE
[MusicBrainz: Import from Amazon] Import Button does not show up on...

### ISSUE THREAD

**Issue by Lotheric** [Goram/MusicBrainz-Import-from-Amazon#1] opened 2015-09-23 16:51 UTC
This link:
http://www.amazon.ca/Anthology-1980-2005-2CD-Bryan-Adams/dp/B000BBOV8U/

perhaps (yet) another type of tracklist.

**Comment by Goram** [comment] 2015-09-23 20:02
Nope, the problem is that I append to the Id "tellAFriendBox_feature_div" and that don´t exists there :o

I play with the thought to find another place for the box. But it has to be the same for all sites. I´ll take a look.

Thanks!

**Comment by Goram** [comment] 2016-05-12 11:38
Hi,

fixed in e454d0e122d93caba3cdefcb1230e5b224f28f2d

Thx!

**Closed as completed** 2016-05-12 11:39 UTC
